spring:
  application:
    name: filme-locadora
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/locadora_db}
    username: ${SPRING_DATASOURCE_USERNAME:locadora_user}
    password: ${SPRING_DATASOURCE_PASSWORD:locadora_pass}
    driver-class-name: org.postgresql.Driver
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.locadora: ${LOGGING_LEVEL_COM_LOCADORA:DEBUG}
    org.springframework.jdbc: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: always